### ISSUE TITLE
 Error 403: {"message"=>"Forbidden", "code"=>"Forbidden"}

### ISSUE THREAD

**Issue by parascse** [microsoft/fastlane-plugin-appcenter#47] opened 2018-12-06 12:03 UTC
Hi,

I am facing this issue while uploading ipa file for ios from fastlane,  also even when i have already created app on app center still it could not find it and shows the same message. please let me know if anything could fix this. 

 --- Step: appcenter_upload ---
 ------------------------------
 Error 403: {"message"=>"Forbidden", "code"=>"Forbidden"}

**Comment by sourabhdadapure** [comment] 2019-02-04 21:40
I'm also facing this same issue. Any fixes yet ?

**Comment by Lcsmarcal** [comment] 2019-02-05 17:20
Same here, any solution?

**Comment by sourabhdadapure** [comment] 2019-02-05 17:23
I was was passing username instead of organization name in the request

**Comment by OreniOS** [comment] 2019-02-12 12:22
Getting the same thing here. 
All was working fine up to a few of days ago.
Today I tried building a release version, but got errors every time on fastlane 2.115.0 when trying to upload to app center.
After I updated fastlane to 2.116.0, got this message followed by:
"App with name XXX not found, create one?". Nothing changed in the Fastfile. 

Anyone has a clue?

**Comment by Jerome1210** [comment] 2019-02-20 03:55
Same issue.

**Comment by liguopku** [comment] 2019-03-05 23:51
I am also running into this issue. Any update or workaround?

**Comment by brynjar** [comment] 2019-03-13 11:23
Take a look at https://github.com/Microsoft/fastlane-plugin-appcenter/issues/15 as well. The use of the words profile/account/organization etc. is all somewhat confusing. For me, I was trying to test with a hockeyapp 'account' that had been brought automatically over to appcenter. Turns out the organization name in the UI is different from what the org in the URL was - and the latter is what I needed to specific in my fastfile config.

**Comment by ushakov-ruslan** [comment] 2019-05-30 08:59
Here is a response form app center support that helped me:

go into your App Center - Build configuration and on the bottom clicking the “Save & Build” button?

This triggers a “soft-reset” on our back-end and reconnects some of the settings that are in the configuration or are automatically detected from the repository.

**Comment by iqbalmineraltown** [comment] 2019-06-10 02:31
I already double-checked the organization url and set token with full access
but still facing this problem

**Comment by DennisPan** [comment] 2019-06-10 03:57
For anyone who are still facing the issue, please reach out to App Center support (via the chat bubble at bottom right of the portal). Most of these will require investigation case by case with your account/app details. If it turns out to be something common, we can circle back to this Issue.

**Comment by AnandWalvekar** [comment] 2019-06-14 12:08
I am also facing the same issue & opened https://github.com/fastlane/fastlane/issues/14907
Also trying with chat bubble which will be reverted within 24hr.

**Comment by v2Nitesh** [comment] 2019-06-19 06:39
I am facing same error and not able to upload the build on the AppCenter. Any idea about below error.

[11:28:31]: Created iOS/Objective-C-Swift app with name "DemoApp" and display name "DemoApp"
[11:28:31]: Starting release upload...
[11:28:32]: Error 403: {"message"=>"Forbidden", "statusCode"=>403, "code"=>"Forbidden"}
[11:28:32]: Starting dSYM upload...
[11:28:33]: Error 403: {"message"=>"Forbidden", "statusCode"=>403, "code"=>"Forbidden"}

**Comment by AnandWalvekar** [comment] 2019-06-21 02:09
<img width="500" alt="Screen Shot 2019-06-19 at 10 29 15 PM" src="https://user-images.githubusercontent.com/349903/59892631-e1334080-9414-11e9-9373-51a185bc95ec.png">
<img width="500" alt="Screen Shot 2019-06-19 at 10 26 36 PM" src="https://user-images.githubusercontent.com/349903/59892632-e1334080-9414-11e9-8b7d-d72b9add111b.png">
<img width="500" alt="Screen Shot 2019-06-19 at 10 25 34 PM" src="https://user-images.githubusercontent.com/349903/59892633-e1cbd700-9414-11e9-9918-e7d8762bfc51.png">

**Comment by v2Nitesh** [comment] 2019-06-21 05:08
@AnandWalvekar - It's working for you ? Can you share steps to fix this?

**Comment by ranterle** [comment] 2019-06-21 16:25
@AnandWalvekar and @v2Nitesh these two look like issues that might have been triggered by some unplanned maintenance. Can you reach out to our support as mentioned in the message above to help us understand your issue better? We're looking into this already but your information will be helpful in an effective resolution.

**Comment by rudiluis** [comment] 2019-06-27 14:26
I'm having this problem too. `403: {"message"=>"Forbidden", "statusCode"=>403, "code"=>"Forbidden"}`

**Comment by evkhramkov** [comment] 2019-06-27 14:35
@rudiluis could you please reach out to App Center support with your case

> For anyone who are still facing the issue, please reach out to App Center support (via the chat bubble at bottom right of the portal). Most of these will require investigation case by case with your account/app details. If it turns out to be something common, we can circle back to this Issue.

**Comment by DennisPan** [comment] 2019-07-02 06:31
Closing this as so far I am not aware of an issue on the plugin side that causes this.

**Closed by DennisPan** 2019-07-02 06:31 UTC

**Comment by alexpchin** [comment] 2019-12-07 11:32
> I was was passing username instead of organization name in the request

How do you pass the organization name? I have transferred from a personal account to an organization and now I get a 403 error

**Comment by rudiluis** [comment] 2019-12-07 14:14
@alexpchin You have to create a new api_token for your organization.

**Comment by chmiiller** [comment] 2020-01-15 17:12
I'm also facing this exact same problem using the plugin on CircleCI. Funny thing is that the Android binary is uploaded successfully, with same token, but iOS doesn't. Any updates?

**Comment by mostafamobiquity** [comment] 2020-01-28 09:54
Same issue. Any idea what's that !!

**Comment by fishercraigj** [comment] 2020-02-21 18:23
Also getting the same issue.  How does this ticket keep getting closed with no actual resolution aside from contact support that takes 2 days to get back to you?

**Comment by ASPetrov** [comment] 2020-05-04 09:23
I managed to solve the same issue by adding:

`strict: 'true'`

**Comment by dikako** [comment] 2020-07-15 07:40
if your problem to upload .apk to app center with jenkins` 403: {"message"=>"Forbidden", "statusCode"=>403, "code"=>"Forbidden"}` 

**Solution:**
You Must Change **App Name** on your **Jenkins Configuration**  sama with your **App Center Project**

References : https://www.logcg.com/en/archives/3290.html

**Comment by voghDev** [comment] 2021-01-14 16:39
I was having the same problem and the cause was `owner name` in my case. For some reason my owner name wasn't my company name (say, `Company`), but was `user-company.com` :man_shrugging: . Once I changed this in my lane:
```
appcenter_upload(
    api_token: "myApiToken",
    owner_name: "user-company.com",
    app_name: "AppName-Android",
    notify_testers: true,
    apk: "app/build/outputs/apk/release/app-release.apk",
    release_notes: "These are the release notes",
    destinations: "Android"
  )
``` 
The upload worked fine.
I discovered my `owner name` with [this tutorial](https://www.logcg.com/en/archives/3290.html) that @dikako mentioned.
What I did is (Linux terminal)
```
 npm install -g appcenter-cli
 appcenter login
 # This took me to a web browser, where I had to copy a Token, and paste it back in the terminal
 appcenter apps list
 # In the output from this last command is where I discovered the right owner name and app name
```
Hope this is helpful for someone else :v:

**Comment by di0** [comment] 2022-01-13 03:59
Creating a new app API token with 'full access' instead of 'read only' option, worked for me.
