### ISSUE TITLE
Always get "Faraday::ConnectionFailed: [!] Broken pipe" when uploading binary

### ISSUE THREAD

**Issue by quzongyao** [microsoft/fastlane-plugin-appcenter#177] opened 2019-12-10 05:50 UTC
We had been using appcenter with this plugin without any issue until Nov, 27th.

Now it always fails when running the upload procedure around 30 secs.

The stdout log looks like 

```
[14:41:13]: ------------------------------
[14:41:13]: --- Step: appcenter_upload ---
[14:41:13]: ------------------------------
[14:41:14]: Starting release upload...
[14:41:14]: Uploading release binary...
[14:41:45]: Broken pipe
+------+----------------------------------------+-------------+
|                      fastlane summary                       |
+------+----------------------------------------+-------------+
| Step | Action                                 | Time (in s) |
+------+----------------------------------------+-------------+
| 1    | default_platform                       | 0           |
| 2    | git rev-list -n 1 --abbrev-commit HEAD | 0           |
| 3    | get_info_plist_value                   | 0           |
| 4    | changelog_from_git_commits             | 0           |
| 💥   | appcenter_upload                       | 32          |
+------+----------------------------------------+-------------+
[14:41:45]: fastlane finished with errors
Looking for related GitHub issues on fastlane/fastlane...
➡️  [Fastlane.swift] Fix string_callback type override
    https://github.com/fastlane/fastlane/pull/15721 [open] 3 💬
    2 days ago
➡️  Broken pipe for upload binary to Hockeyapp
    https://github.com/fastlane/fastlane/issues/14699 [closed] 47 💬
    02 Jul 2019
➡️  Broken pipe for upload binary to Hockeyapp
    https://github.com/fastlane/fastlane/issues/14698 [closed] 0 💬
    30 Jun 2019
and 25 more at: https://github.com/fastlane/fastlane/search?q=Broken%20pipe&type=Issues&utf8=✓
🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/djij-solution-deployment/.rbenv/versions/2.5.0/bin/fastlane)
Faraday::ConnectionFailed: [!] Broken pipe
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/2.5.0/openssl/buffering.rb:325:in `syswrite'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/2.5.0/openssl/buffering.rb:325:in `do_write'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/2.5.0/openssl/buffering.rb:344:in `block in write'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/2.5.0/openssl/buffering.rb:343:in `each'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/2.5.0/openssl/buffering.rb:343:in `inject'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/2.5.0/openssl/buffering.rb:343:in `write'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/http/generic_request.rb:206:in `copy_stream'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/http/generic_request.rb:206:in `send_request_with_body_stream'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/http/generic_request.rb:123:in `exec'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/http.rb:1492:in `block in transport_request'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/http.rb:1491:in `catch'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/http.rb:1491:in `transport_request'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/http.rb:1464:in `request'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/http.rb:1457:in `block in request'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/http.rb:910:in `start'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/2.5.0/net/http.rb:1455:in `request'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:87:in `perform_request'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:43:in `block in call'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:38:in `call'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:87:in `perform_with_redirection'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:75:in `call'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:31:in `call'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/request/url_encoded.rb:15:in `call'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/request/multipart.rb:15:in `call'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/rack_builder.rb:143:in `build_response'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/connection.rb:387:in `run_request'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/connection.rb:175:in `post'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-plugin-appcenter-1.7.1/lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb:203:in `upload_build'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-plugin-appcenter-1.7.1/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:185:in `run_release_upload'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-plugin-appcenter-1.7.1/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:289:in `run'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:204:in `upload_appcenter'
  Fastfile:246:in `block (2 levels) in parsing_binding'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.137.0/bin/fastlane:23:in `<top (required)>'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/bin/fastlane:23:in `load'
  /Users/djij-solution-deployment/.rbenv/versions/2.5.0/bin/fastlane:23:in `<top (required)>'
```

The fastlane code looks like 
```
    appcenter_upload(
      api_token: "XXX",
      owner_name: "Team Name",
      app_name: "App Name",
      file: "./builds/#{ipaname}.ipa",
      dsym: "./builds/#{ipaname}.app.dSYM.zip",
      release_notes: "- Build: __#{build_number}__ \n- SHA: __#{sha}__ \n- Environment: __#{channel::Environment}__ \n- Configuration: __#{channel::Configuration}__ \n- Job Name: __#{job_name}__\n- Latest commits\n#{change_log} \n\n- Published by Fastlane",
      notify_testers: true,
      should_clip: false
    )
```

Totally get lost, anything we could work out?

**Comment by jpeg-ms** [comment] 2019-12-10 19:25
Have you tried an older version of this plugin?
If you modify the file `fastlane/Pluginfile` you can target an older version of `fastlane-plugin-appcenter`. If the problem is solved, please let us know which version works for you.

If the problem persists, it might be due to a change in fastlane (if you've updated it recently). Or it can be due to a change in App Center upload service. If you haven't updated fastlane recently, we will have to double check on our side.

How large are you DSYM files? And how long would it take to upload normally?

**Comment by quzongyao** [comment] 2019-12-11 07:37
Thank you for the reply.

1. dSYM is around 34 MB, and I dont think it could hit your 256 MB Limit.
2. Now things seems to get complicated, and we could confirm that it is NOT 100% reproducible issue.
   2.1 We changed our network from company's internal LAN to a pocket wifi, by far, it succeeded every time.
   2.2. Even we use company's internal LAN, the issue reproduces occasionally. If we upload at 00:00 AM GMT+9 (which is our daily build's scheduled time), it by far, failed every time.
   2.3. If we start to debug at our work time, it reproduces sometimes, but not every time.
   2.4. We tried to turn off our firewall, it does not seem helping, nor worsen it.

Now we highly doubt that, there is something left in our firewall setting that we ignored, or appcenter.ms just banned our company's IP address.
Since we have a rotation mechanism for our IP exits, this might hit the black list.

**Comment by ramilexe** [comment] 2019-12-16 13:17
The same issue for me. I tried another attempt and it worked. 
It is NOT 100% reproducible issue as mentioned @quzongyao

**Comment by Ajaykn21** [comment] 2019-12-20 07:01
@quzongyao Please let us know if you are still facing the issue and persistent.
We need details of your appName and if you are not comfortable sharing your app name here, you can raise a support ticket using blue chat button in AppCenter.
<img width="573" alt="image" src="https://user-images.githubusercontent.com/40024974/71236262-d9ac1000-2341-11ea-9474-a5a0924756fe.png">

**Comment by quzongyao** [comment] 2019-12-23 01:22
> @quzongyao Please let us know if you are still facing the issue and persistent.
> We need details of your appName and if you are not comfortable sharing your app name here, you can raise a support ticket using blue chat button in AppCenter.
> <img alt="image" width="573" src="https://user-images.githubusercontent.com/40024974/71236262-d9ac1000-2341-11ea-9474-a5a0924756fe.png">

Hey thank you for the reply.

The issue still persists and we now have no method to go further right now.

We have several apps in our organization
https://appcenter.ms/orgs/DJIJ-Solution-Team/apps/DJI-GS-Pro-New
https://appcenter.ms/orgs/DJIJ-Solution-Team/apps/ENT-GS-Pro-AC

They are experiencing the same issue.

**Comment by stel** [comment] 2019-12-23 11:46
I've faced a similar issue, fastlane didn't crash though but no symbols were uploaded.

This is the only output I got from `appcenter_upload` step:
```
[12:30:42]: ------------------------------
[12:30:42]: --- Step: appcenter_upload ---
[12:30:42]: ------------------------------
NOTE: Inheriting Faraday::Error::ClientError is deprecated; use Faraday::ClientError instead. It will be removed in or after version 1.0
Faraday::Error::ClientError.inherited called from /usr/local/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:6.
```

Reproduces constantly on both 1.7.0 and 1.7.1, downgrading to 1.6.0 resolved the issue.

**Comment by renardmf** [comment] 2020-02-17 23:39
> I've faced a similar issue, fastlane didn't crash though but no symbols were uploaded.
> 
> This is the only output I got from `appcenter_upload` step:
> 
> ```
> [12:30:42]: ------------------------------
> [12:30:42]: --- Step: appcenter_upload ---
> [12:30:42]: ------------------------------
> NOTE: Inheriting Faraday::Error::ClientError is deprecated; use Faraday::ClientError instead. It will be removed in or after version 1.0
> Faraday::Error::ClientError.inherited called from /usr/local/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:6.
> ```
> 
> Reproduces constantly on both 1.7.0 and 1.7.1, downgrading to 1.6.0 resolved the issue.

Yes, downgrading to 1.6.0 resolved the issue for me as well.

**Comment by BsBrabi** [comment] 2020-02-19 13:37
We also faced the issue with 1.8.0.
Setting the distribute-timeout option of the plugin seems to fix the problem for us:
`ENV["APPCENTER_DISTRIBUTE_TIMEOUT"] = "300" # = 5 minutes`

**Comment by jp-andre** [comment] 2020-02-21 00:29
Hi everyone!
Unfortunately, we still haven't been able to clearly reproduce from our end.

For information, the build upload uses a POST call which should respect the value of `timeout`. But the dSYM upload uses a PUT call and somehow the timeout is not respected. To fix this we likely would have to change which ruby HTTP library we use.

When simulating timeouts (eg. by uploading a file that's too large on a slow network), I get various random errors from Faraday. This includes `broken pipe` but sometimes the error message is different.

I had a look at the changes between `v1.6.0` and `v1.8.0` and there was no change to the network calls, so I believe the issue is either not 100% reproducible, or it comes from a different dependency version being used by different users. We don't provide a `Gemfile.lock` here so the dependency versions are not fixed.

**Comment by jp-andre** [comment] 2020-05-18 07:59
I believe this is solved by using `timeout` for app binaries but no solution was found for large dSYM. See the comments on #140.

I will close this now.

**Closed by jp-andre** 2020-05-18 07:59 UTC
Labels: question
