### ISSUE TITLE
Upload to appcenter aborted

### ISSUE THREAD

**Issue by adelinoubli** [microsoft/fastlane-plugin-appcenter#262] opened 2021-01-19 14:10 UTC
Hello, does anyone else encountering this issue while uploading to appcenter ?
im using the latest version of fastlane 2.171.0 and appcenter plugin version 1.11.0

INFO [2021-01-19 14:41:56.22]: [32m------------------------------[0m
INFO [2021-01-19 14:41:56.22]: [32m--- Step: appcenter_upload ---[0m
INFO [2021-01-19 14:41:56.22]: [32m------------------------------[0m
INFO [2021-01-19 14:41:57.29]: Starting release upload...
INFO [2021-01-19 14:41:58.17]: Setting Metadata...
INFO [2021-01-19 14:41:58.88]: Metadata set
INFO [2021-01-19 14:41:58.88]: Uploading release binary...
INFO [2021-01-19 14:43:00.80]: DEBUG: Retryable error uploading binary 0: Net::ReadTimeout with #<TCPSocket:(closed)>
INFO [2021-01-19 14:43:21.00]: Chunk uploaded
INFO [2021-01-19 14:44:24.28]: DEBUG: Retryable error uploading binary 0: Net::ReadTimeout with #<TCPSocket:(closed)>
INFO [2021-01-19 14:45:31.08]: DEBUG: Retryable error uploading binary 0: Net::ReadTimeout with #<TCPSocket:(closed)>
ERROR [2021-01-19 14:46:38.89]: [31mError uploading binary 0: Net::ReadTimeout with #<TCPSocket:(closed)>[0m
WARN [2021-01-19 14:46:38.90]: [33m[33mLane Context:[0m
ERROR [2021-01-19 14:46:38.90]: [31mUpload aborted[0m

**Comment by avinash-ivy** [comment] 2021-03-25 11:02
Hi AppCenter plugin team,
We are facing this issue every time from past few days. This is happening more with builds with larger iPa file size.
Issue happens with even latest Fastlane version 2.178.0

This is really frustrating as almost all uploads are getting failed and we are unable to distribute to other members of the team.

Here are the logs - 

> [12:55:02]: 
[12:55:02]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[12:55:02]: [31mWARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables[0m
+---------------------------+---------+--------------------------------+
|                             [32mUsed plugins[0m                             |
+---------------------------+---------+--------------------------------+
| Plugin                    | Version | Action                         |
+---------------------------+---------+--------------------------------+
| fastlane-plugin-appcenter | 1.11.0  | appcenter_fetch_version_number |
|                           |         | appcenter_fetch_devices        |
|                           |         | appcenter_upload               |
+---------------------------+---------+--------------------------------+

[12:55:16]: [32m----------------------------------------[0m
[12:55:16]: [32m--- Step: Verifying fastlane version ---[0m
[12:55:16]: [32m----------------------------------------[0m
[12:55:16]: Your fastlane version 2.151.2 matches the minimum requirement of 2.53.1  ✅
[12:55:16]: [32m------------------------------[0m
[12:55:16]: [32m--- Step: default_platform ---[0m
[12:55:16]: [32m------------------------------[0m
/usr/local/Cellar/fastlane/2.151.2/libexec/gems/fastlane-2.151.2/fastlane_core/lib/fastlane_core/ui/interface.rb:141: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/Cellar/fastlane/2.151.2/libexec/gems/fastlane-2.151.2/fastlane_core/lib/fastlane_core/ui/errors/fastlane_error.rb:9: warning: The called method `initialize' is defined here
[12:55:16]: [32mDriving the lane 'ios buildEurobetIT' 🚀[0m
[12:55:16]: [32m--------------------------------------[0m
[12:55:16]: [32m--- Step: increment_version_number ---[0m
[12:55:16]: [32m--------------------------------------[0m
[Build got completed]
[13:25:57]: [32mSuccessfully exported and compressed dSYM file[0m
[13:25:57]: [32mSuccessfully exported and signed the ipa file:[0m
[13:25:57]: /Users/test/builds/ee645947/0/Mobile_Poker_iOS/Poker/ApplicationPoker/EurobetIT.ipa
[13:25:57]: [32m------------------------------[0m
[13:25:57]: [32m--- Step: appcenter_upload ---[0m
[13:25:57]: [32m------------------------------[0m
[13:25:59]: Starting release upload...
[13:26:00]: Setting Metadata...
[13:26:02]: Metadata set
[13:26:02]: Uploading release binary...
[13:26:09]: Chunk uploaded
[13:26:14]: Chunk uploaded
[13:26:22]: Chunk uploaded
[13:26:33]: Chunk uploaded
[13:27:04]: Chunk uploaded
[13:27:32]: Chunk uploaded
[13:27:44]: Chunk uploaded
[13:27:49]: Chunk uploaded
[13:28:41]: Chunk uploaded
[13:28:52]: Chunk uploaded
[13:28:57]: Chunk uploaded
[13:29:12]: Chunk uploaded
[13:29:16]: Chunk uploaded
[13:29:21]: Chunk uploaded
[13:29:25]: Chunk uploaded
[13:30:29]: DEBUG: Retryable error uploading binary 0: Net::ReadTimeout with #<TCPSocket:(closed)>
[13:31:37]: DEBUG: Retryable error uploading binary 0: Net::ReadTimeout with #<TCPSocket:(closed)>
[13:31:46]: Chunk uploaded
[13:32:03]: Chunk uploaded
[13:32:08]: Chunk uploaded
[13:32:13]: Chunk uploaded
[13:32:59]: Chunk uploaded
[13:33:51]: Chunk uploaded
[13:34:20]: Chunk uploaded
[13:34:25]: Chunk uploaded
[13:34:36]: Chunk uploaded
[13:34:40]: Chunk uploaded
[13:35:23]: Chunk uploaded
[13:35:52]: Chunk uploaded
[13:35:56]: Chunk uploaded
[13:36:57]: Chunk uploaded
[13:37:18]: Chunk uploaded
[13:39:06]: Chunk uploaded
[13:39:20]: Chunk uploaded
[13:39:25]: Chunk uploaded
[13:39:30]: Chunk uploaded
[13:40:31]: Chunk uploaded
[13:41:55]: Chunk uploaded
[13:42:06]: Chunk uploaded
[13:43:10]: DEBUG: Retryable error uploading binary 0: Net::ReadTimeout with #<TCPSocket:(closed)>
[13:45:10]: Chunk uploaded
[13:46:04]: Chunk uploaded
[13:46:08]: Chunk uploaded
[13:46:12]: Chunk uploaded
[13:48:33]: Chunk uploaded
[13:49:35]: Chunk uploaded
[13:49:59]: Chunk uploaded
[13:50:04]: Chunk uploaded
[13:50:21]: Chunk uploaded
[13:50:56]: Chunk uploaded
[13:51:59]: DEBUG: Retryable error uploading binary 0: Net::ReadTimeout with #<TCPSocket:(closed)>
[13:55:21]: Chunk uploaded
[13:59:17]: Chunk uploaded
[14:02:08]: Chunk uploaded
[14:02:56]: Chunk uploaded
[14:03:08]: Chunk uploaded
[14:04:04]: Chunk uploaded
[14:04:12]: Chunk uploaded
[14:05:00]: Chunk uploaded
[14:05:10]: Chunk uploaded
[14:06:05]: Chunk uploaded
[14:07:33]: Chunk uploaded
[14:08:07]: Chunk uploaded
[14:10:09]: Chunk uploaded
[14:11:13]: Chunk uploaded
[14:12:05]: Chunk uploaded
[14:12:39]: Chunk uploaded
[14:13:06]: Chunk uploaded
[14:14:10]: Chunk uploaded
[14:15:38]: Chunk uploaded
[14:17:06]: Chunk uploaded
[14:17:45]: Chunk uploaded
[14:18:56]: Chunk uploaded
[14:19:53]: Chunk uploaded
[14:20:11]: Chunk uploaded
[14:21:30]: Chunk uploaded
[14:22:06]: Chunk uploaded
[14:24:19]: Chunk uploaded
[14:24:44]: Chunk uploaded
[14:25:03]: Chunk uploaded
[14:25:40]: Chunk uploaded
[14:26:04]: Chunk uploaded
[14:26:10]: Chunk uploaded
[14:26:55]: Chunk uploaded
[14:27:15]: Chunk uploaded
[14:28:00]: Chunk uploaded
[14:28:05]: Chunk uploaded
[14:28:58]: Chunk uploaded
[14:29:53]: Chunk uploaded
[14:30:26]: Chunk uploaded
[14:31:53]: Chunk uploaded
[14:32:04]: Chunk uploaded
[14:32:19]: Chunk uploaded
[14:32:25]: Chunk uploaded
[14:32:39]: Chunk uploaded
[14:32:44]: Chunk uploaded
[14:33:00]: Chunk uploaded
[14:33:07]: Chunk uploaded
[14:35:06]: Chunk uploaded
[14:35:18]: Chunk uploaded
[14:35:36]: Chunk uploaded
[14:36:00]: Chunk uploaded
[14:36:54]: Chunk uploaded
[14:37:15]: Chunk uploaded
[14:37:45]: Chunk uploaded
[14:38:08]: Chunk uploaded
[14:38:13]: Chunk uploaded
[14:39:02]: Chunk uploaded
[14:41:27]: Chunk uploaded
[14:42:21]: Chunk uploaded
[14:44:45]: Chunk uploaded
[14:45:40]: Chunk uploaded
[14:45:57]: Chunk uploaded
[14:46:09]: Chunk uploaded
[14:46:53]: Chunk uploaded
[14:48:19]: Chunk uploaded
[14:48:41]: Chunk uploaded
[14:49:23]: Chunk uploaded
[14:49:41]: Chunk uploaded
[14:49:46]: Chunk uploaded
[14:50:00]: Chunk uploaded
[14:50:13]: Chunk uploaded
[14:50:23]: Chunk uploaded
[14:51:01]: Chunk uploaded
[14:52:05]: DEBUG: Retryable error uploading binary 0: Net::ReadTimeout with #<TCPSocket:(closed)>
[14:53:25]: Chunk uploaded
[14:54:40]: Chunk uploaded
[14:54:59]: Chunk uploaded
[14:55:50]: Chunk uploaded
[14:56:00]: Chunk uploaded
[14:56:05]: Chunk uploaded
[14:56:14]: Chunk uploaded
[14:58:01]: Chunk uploaded
[14:58:10]: Chunk uploaded
[14:59:39]: Chunk uploaded
[15:00:03]: Chunk uploaded
[15:00:10]: Chunk uploaded
[15:00:16]: Chunk uploaded
[15:00:38]: Chunk uploaded
[15:00:43]: Chunk uploaded
[15:00:56]: Chunk uploaded
[15:01:05]: Chunk uploaded
[15:01:16]: Chunk uploaded
[15:01:30]: Chunk uploaded
[15:01:46]: Chunk uploaded
[15:01:52]: Chunk uploaded
[15:01:56]: Chunk uploaded
[15:02:11]: Chunk uploaded
[15:02:54]: Chunk uploaded
[15:03:06]: Chunk uploaded
[15:03:11]: Chunk uploaded
[15:03:31]: Chunk uploaded
[15:04:34]: DEBUG: Retryable error uploading binary 0: Net::ReadTimeout with #<TCPSocket:(closed)>
[15:04:43]: Chunk uploaded
[15:04:47]: Chunk uploaded
[15:04:51]: Chunk uploaded
[15:04:55]: Chunk uploaded
[15:05:03]: Chunk uploaded
[15:05:08]: Chunk uploaded
[15:05:19]: Chunk uploaded
[15:05:38]: Chunk uploaded
[15:05:42]: Chunk uploaded
[15:06:46]: DEBUG: Retryable error uploading binary 0: Net::WriteTimeout with #<TCPSocket:(closed)>
[15:06:55]: Chunk uploaded
[15:06:59]: Chunk uploaded
[15:07:03]: Chunk uploaded
[15:07:06]: Chunk uploaded
[15:07:10]: Chunk uploaded
[15:07:44]: Chunk uploaded
[15:07:53]: Chunk uploaded
[15:07:58]: Chunk uploaded
[15:08:04]: Chunk uploaded
[15:08:11]: Chunk uploaded
[15:08:16]: Chunk uploaded
[15:08:22]: Chunk uploaded
[15:08:31]: Chunk uploaded
[15:08:36]: Chunk uploaded
[15:08:51]: Chunk uploaded
[15:08:56]: Chunk uploaded
[15:09:00]: Chunk uploaded
[15:09:12]: Chunk uploaded
[15:10:17]: DEBUG: Retryable error uploading binary 0: Net::ReadTimeout with #<TCPSocket:(closed)>
[15:10:29]: Chunk uploaded
[15:10:33]: Chunk uploaded
[15:11:16]: Chunk uploaded
[15:12:19]: DEBUG: Retryable error uploading binary 0: Net::ReadTimeout with #<TCPSocket:(closed)>
[15:12:35]: Chunk uploaded
[15:12:40]: Chunk uploaded
[15:12:52]: Chunk uploaded
[15:12:57]: Chunk uploaded
[15:13:07]: Chunk uploaded
[15:13:11]: Chunk uploaded
[15:13:22]: Chunk uploaded
[15:13:36]: Chunk uploaded
[15:13:41]: Chunk uploaded
[15:14:05]: Chunk uploaded
[15:14:17]: Chunk uploaded
[15:14:23]: Chunk uploaded
[15:14:29]: Chunk uploaded
[15:15:33]: DEBUG: Retryable error uploading binary 0: Net::ReadTimeout with #<TCPSocket:(closed)>
[15:16:42]: DEBUG: Retryable error uploading binary 0: Net::ReadTimeout with #<TCPSocket:(closed)>
[15:17:50]: [31mError uploading binary 0: Net::ReadTimeout with #<TCPSocket:(closed)>[0m
[15:18:26]: [31mUpload aborted[0m

+------+-----------------------------+-------------+
|                 [32mfastlane summary[0m                 |
+------+-----------------------------+-------------+
| Step | Action                      | Time (in s) |
+------+-----------------------------+-------------+
| 1    | Verifying fastlane version  | 0           |
| 2    | default_platform            | 0           |
| 3    | increment_version_number    | 7           |
| 4    | xcode_select                | 0           |
| 5    | git_branch                  | 0           |
| 6    | get_build_number_repository | 17          |
| 7    | get_build_number            | 0           |
| 8    | increment_build_number      | 1           |
| 9    | clear_derived_data          | 3           |
| 10   | gym                         | 1811        |
| 💥   | [31mappcenter_upload[0m            | 6712        |
| 12   | is_ci                       | 0           |
| 13   | reset_git_repo              | 35          |
| 14   | slack                       | 1           |
+------+-----------------------------+-------------+

[15:18:26]: [31mfastlane finished with errors[0m
[31m
[!] Upload aborted[0m

**Comment by avinash-ivy** [comment] 2021-03-26 09:44
Another instance of upload failure, this time it happened in 13 minutes of starting upload.

> [14:13:05]: Successfully exported and compressed dSYM file
[14:13:05]: Successfully exported and signed the ipa file:
[14:13:05]: /Users/test/builds/9a9ef376/0/Mobile_Poker_iOS/Poker/ApplicationPoker/EurobetIT.ipa
[14:13:05]: ------------------------------
[14:13:05]: --- Step: appcenter_upload ---
[14:13:05]: ------------------------------
[14:13:07]: Starting release upload...
[14:13:08]: Setting Metadata...
[14:13:09]: Metadata set
[14:13:09]: Uploading release binary...
[14:13:13]: Chunk uploaded
[14:13:18]: Chunk uploaded
[14:13:22]: Chunk uploaded
[14:13:28]: Chunk uploaded
[14:13:32]: Chunk uploaded
[14:13:37]: Chunk uploaded
[14:13:43]: Chunk uploaded
[14:13:48]: Chunk uploaded
[14:13:51]: Chunk uploaded
[14:13:56]: Chunk uploaded
[14:14:00]: Chunk uploaded
[14:14:04]: Chunk uploaded
[14:14:09]: Chunk uploaded
[14:14:12]: Chunk uploaded
[14:14:17]: Chunk uploaded
[14:14:20]: Chunk uploaded
[14:14:25]: Chunk uploaded
[14:14:29]: Chunk uploaded
[14:14:32]: Chunk uploaded
[14:14:36]: Chunk uploaded
[14:14:41]: Chunk uploaded
[14:14:45]: Chunk uploaded
[14:14:51]: Chunk uploaded
[14:14:54]: Chunk uploaded
[14:14:58]: Chunk uploaded
[14:15:03]: Chunk uploaded
[14:15:06]: Chunk uploaded
[14:15:10]: Chunk uploaded
[14:15:16]: Chunk uploaded
[14:15:20]: Chunk uploaded
[14:15:24]: Chunk uploaded
[14:15:29]: Chunk uploaded
[14:15:33]: Chunk uploaded
[14:15:37]: Chunk uploaded
[14:15:44]: Chunk uploaded
[14:15:53]: Chunk uploaded
[14:15:58]: Chunk uploaded
[14:16:02]: Chunk uploaded
[14:16:07]: Chunk uploaded
[14:16:11]: Chunk uploaded
[14:16:15]: Chunk uploaded
[14:16:20]: Chunk uploaded
[14:16:24]: Chunk uploaded
[14:16:31]: Chunk uploaded
[14:16:36]: Chunk uploaded
[14:16:40]: Chunk uploaded
[14:16:44]: Chunk uploaded
[14:16:49]: Chunk uploaded
[14:16:53]: Chunk uploaded
[14:16:58]: Chunk uploaded
[14:17:02]: Chunk uploaded
[14:17:06]: Chunk uploaded
[14:17:10]: Chunk uploaded
[14:17:13]: Chunk uploaded
[14:17:18]: Chunk uploaded
[14:17:22]: Chunk uploaded
[14:17:27]: Chunk uploaded
[14:17:30]: Chunk uploaded
[14:17:35]: Chunk uploaded
[14:17:40]: Chunk uploaded
[14:17:43]: Chunk uploaded
[14:17:47]: Chunk uploaded
[14:17:52]: Chunk uploaded
[14:17:58]: Chunk uploaded
[14:18:03]: Chunk uploaded
[14:18:10]: Chunk uploaded
[14:18:13]: Chunk uploaded
[14:18:20]: Chunk uploaded
[14:18:23]: Chunk uploaded
[14:18:27]: Chunk uploaded
[14:18:31]: Chunk uploaded
[14:18:36]: Chunk uploaded
[14:18:41]: Chunk uploaded
[14:18:52]: Chunk uploaded
[14:19:02]: Chunk uploaded
[14:19:07]: Chunk uploaded
[14:19:11]: Chunk uploaded
[14:19:17]: Chunk uploaded
[14:19:27]: Chunk uploaded
[14:19:31]: Chunk uploaded
[14:19:35]: Chunk uploaded
[14:19:40]: Chunk uploaded
[14:19:43]: Chunk uploaded
[14:19:48]: Chunk uploaded
[14:19:52]: Chunk uploaded
[14:19:56]: Chunk uploaded
[14:20:01]: Chunk uploaded
[14:20:06]: Chunk uploaded
[14:20:10]: Chunk uploaded
[14:20:14]: Chunk uploaded
[14:20:19]: Chunk uploaded
[14:20:25]: Chunk uploaded
[14:20:31]: Chunk uploaded
[14:20:37]: Chunk uploaded
[14:20:42]: Chunk uploaded
[14:20:49]: Chunk uploaded
[14:20:54]: Chunk uploaded
[14:20:58]: Chunk uploaded
[14:21:05]: Chunk uploaded
[14:21:17]: Chunk uploaded
[14:21:22]: Chunk uploaded
[14:21:28]: Chunk uploaded
[14:21:32]: Chunk uploaded
[14:21:36]: Chunk uploaded
[14:21:44]: Chunk uploaded
[14:21:50]: Chunk uploaded
[14:21:53]: Chunk uploaded
[14:21:58]: Chunk uploaded
[14:22:02]: Chunk uploaded
[14:22:08]: Chunk uploaded
[14:22:12]: Chunk uploaded
[14:22:18]: Chunk uploaded
[14:22:22]: Chunk uploaded
[14:22:28]: Chunk uploaded
[14:22:40]: Chunk uploaded
[14:22:45]: Chunk uploaded
[14:22:50]: Chunk uploaded
[14:22:58]: Chunk uploaded
[14:23:05]: Chunk uploaded
[14:23:15]: Chunk uploaded
[14:23:20]: Chunk uploaded
[14:23:48]: Chunk uploaded
[14:23:57]: Chunk uploaded
[14:24:03]: Chunk uploaded
[14:24:11]: Chunk uploaded
[14:24:14]: Chunk uploaded
[14:24:24]: Chunk uploaded
[14:24:30]: Chunk uploaded
[14:24:34]: Chunk uploaded
[14:24:38]: Chunk uploaded
[14:24:45]: Chunk uploaded
[14:24:50]: Chunk uploaded
[14:24:54]: Chunk uploaded
[14:25:57]: DEBUG: Retryable error uploading binary 0: Net::ReadTimeout with #<TCPSocket:(closed)>
[14:26:32]: DEBUG: Retryable error uploading binary 0: Failed to open TCP connection to file.appcenter.ms:443 (getaddrinfo: nodename nor servname provided, or not known)
[14:27:07]: Error uploading binary 0: Failed to open TCP connection to file.appcenter.ms:443 (getaddrinfo: nodename nor servname provided, or not known)
[14:27:07]: -------------------
[14:27:07]: --- Step: is_ci ---
[14:27:07]: -------------------
[14:27:07]: ----------------------------
[14:27:07]: --- Step: reset_git_repo ---
[14:27:07]: ----------------------------
[14:27:07]: $ git reset --hard HEAD
[14:27:09]: ▸ HEAD is now at c43df2ab5e fastlane syntax issue fix
[14:27:09]: $ git clean -qfdx
[14:27:10]: Git repo was reset and cleaned back to a pristine state.
[14:27:10]: -------------------
[14:27:10]: --- Step: slack ---
[14:27:10]: -------------------
[14:27:40]: Exception: Failed to open TCP connection to hooks.slack.com:443 (getaddrinfo: nodename nor servname provided, or not known)
[14:27:40]: An error occurred while executing the `error` block:
[14:27:40]: Error pushing Slack message, maybe the integration has no permission to post on this channel? Try removing the channel parameter in your Fastfile, this is usually caused by a misspelled or changed group/channel name or an expired SLACK_URL
+-------------------------+-------------------------------------------------------------------------------------------------+
|                                                       Lane Context                                                        |
+-------------------------+-------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM        | ios                                                                                             |
| PLATFORM_NAME           | ios                                                                                             |
| LANE_NAME               | ios buildEurobetIT                                                                              |
| VERSION_NUMBER          | 6.7.6                                                                                           |
| BUILD_NUMBER_REPOSITORY | c43df2ab5e                                                                                      |
| BUILD_NUMBER            | 2.0.0-EurobetIT-Dev.Amarnath-Labels-LadbrokesBE.c43df2ab5e.155784                               |
| IPA_OUTPUT_PATH         | /Users/test/builds/9a9ef376/0/Mobile_Poker_iOS/Poker/ApplicationPoker/EurobetIT.ipa             |
| XCODEBUILD_ARCHIVE      | /Users/test/Library/Developer/Xcode/Archives/2021-03-26/EurobetIT 2021-03-26 13.57.06.xcarchive |
| DSYM_OUTPUT_PATH        | /Users/test/builds/9a9ef376/0/Mobile_Poker_iOS/Poker/ApplicationPoker/EurobetIT.app.dSYM.zip    |
+-------------------------+-------------------------------------------------------------------------------------------------+
[14:27:40]: Upload aborted

**Comment by avinash-ivy** [comment] 2021-08-31 13:05
@evkhramkov can you guide us on this? This is really a blocker for us as the uploads are now manually uploaded and it is taking around 45 minutes for 1.6 GB ipa. We are uploading around 10-12 IPAs per day.
Can you help us in identifying where the error is?

**Comment by DmitriyKirakosyan** [comment] 2022-06-10 04:24
Hi @adelinoubli and @avinash-ivy , are you still experiencing this issue?

**Comment by DmitriyKirakosyan** [comment] 2023-04-22 10:07
I'm closing. Please let me know if anyone still faces it.

**Closed by DmitriyKirakosyan** 2023-04-22 10:07 UTC

**Comment by DmitriyKirakosyan** [comment] 2024-10-21 07:26
Hi @METoubar , what logs do you have before you get "Upload aborted"? Have you tried to do the same using `appcenter-cli`?
