### ISSUE TITLE
AppCenter URLs expire

### ISSUE THREAD

**Issue by adityakhatkhate** [microsoft/fastlane-plugin-appcenter#195] opened 2020-02-21 15:56 UTC
Hi Team,

We are noticing that AppCenter URL generated by the plugin expire in typically one or two days. This is an issue for our developers when they want to go back to these notifications and try accessing them. Is there a way they can be set to not expire? and if not, can this option be made available. 

Error message for the expired URL reads below : 

```
<Error>
<Code>AuthenticationFailed</Code>
<Message>
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:f XXXXXXXXXXXXXX Time:2020-02-21T15:56:36.3571039Z
</Message>
<AuthenticationErrorDetail>
Signed expiry time [Thu, 20 Feb 2020 23:02:53 GMT] must be after signed start time [Fri, 21 Feb 2020 15:56:36 GMT]
</AuthenticationErrorDetail>
</Error>
```

Best,
Aditya

**Comment by jp-andre** [comment] 2020-02-24 02:09
Hi,

Is this specific to the plugin or is the behavior the same when using the portal? It sounds like this might be an issue with App Center releases. I tried from portal today and got a URL like:
```
https://install.appcenter.ms/users/<user>/apps/<app>/releases/<id>?source=email&tid=<some-kind-of-id>
```
The same link without `&tid=<id>` points to the same release, but has no credentials of any kind and can't expire.
Or are you talking about the "real" download URL (which is not easily visible from a browser)? That one has a token and will expire by design.

If the behavior is the same when using the portal, your question should be redirected to the main repo for app center.

Best,
JP

**Comment by ranmeirman** [comment] 2020-02-24 18:06
@jp-andre I am facing the same issue with the download url provided after uploading the binary via the Rest API. Something like: `https://appcenter-filemanagement-distrib5ede6f06e.azureedge.net/<id>/<apk_filename>?sv=<some_signature_with_params>`. This URL expires after 24 hours

**Comment by adityakhatkhate** [comment] 2020-02-24 18:19
@jp-andre This is true for the urls that begin with `https://appcenter-filemanagement-distrib1ede6f06e.azureedge.net/` as mentioned by @ranmeirman. These correspond to the `install_url` ->
`lane_context[SharedValues::APPCENTER_BUILD_INFORMATION])['install_url']` from the lane_context in our case. The URLs are distributed to testers and developers as notifications on slack. Since they expire in 24 hours, testers have to now grab these files from appcenter directly if they are looking at these notifications post 24 hours or want to revisit an older notification, which adds to the complexity of managing a single place for notifications/download/install/etc.

**Comment by jp-andre** [comment] 2020-02-25 08:52
Hi!

Thanks @adityakhatkhate and @ranmeirman for the precisions, this makes it easier to understand exactly what we are talking about. I could test myself and observe the temporary URLs in the returned object.

Are you using the webhook slack integration directly from App Center?
Or is it custom code that uses the value of `lane_context[SharedValues::APPCENTER_BUILD_INFORMATION]['install_url']`?

**Comment by ranmeirman** [comment] 2020-02-26 02:24
I am using custom code. Is there a way to get a non temporary url, or will it require to do another api call to get the proper link every time it is required?

**Comment by jp-andre** [comment] 2020-02-26 04:42
I'll see what we can do to provide a permanent URL. We may end up reusing logic that's already there in the plugin code, and constructs the `https://install.appcenter.ms/...` URL, but I've asked my colleagues whether there would be another solution first.

**Comment by adityakhatkhate** [comment] 2020-03-18 00:16
@jp-andre Wanted to follow up on this one to see if there were any updates. Our developers and qa engineers have been circling back quite often to see if there is a resolution in place for this.

**Comment by rivaros** [comment] 2022-10-25 06:45
Looks like in 2 years the issue is still there :)

**Comment by DmitriyKirakosyan** [comment] 2024-06-21 07:54
As we do not have plans to add support for this feature in the next year, I'm closing the issue.

**Closed by DmitriyKirakosyan** 2024-06-21 07:54 UTC
Labels: bug
