### ISSUE TITLE
Cannot upload ios via appcenter_upload in Travis CI.

### ISSUE THREAD

**Issue by ginesdeka** [microsoft/fastlane-plugin-appcenter#249] opened 2020-10-02 09:13 UTC
Error uploading binary 500: {"error"=>{"code"=>500, "message"=>"The key '�7q<o��M �vUҞ�z�--d|������\u0010�b{A�^�Ğ�D[�Ë��\u0013y{�E�\u007F�l��\f�\u0012�5Y�\f�\u0019?��wQD \t�\u0000�����D' is invalid JQuery syntax because it is missing a closing bracket.\r\nParameter name: key"}}

**Comment by lumaxis** [comment] 2020-10-05 22:53
@ginesdeka This is likely a duplicate of #247, can you please try if `v1.10.0` fixes your issue?

**Closed by lumaxis** 2020-10-05 22:53 UTC
