### ISSUE TITLE
Failure to upload dSYM does not fail the build

### ISSUE THREAD

**Issue by kokenjr** [microsoft/fastlane-plugin-appcenter#252] opened 2020-10-21 15:13 UTC
When attempting to upload a dSYM we got the following error:

```
Error 502: {"message"=>"internal error", "err_message"=>"error: activity_name: graph router, exception: ETIMEDOUT, current_request_url: /v0.1/apps/[redacted]/[redacted]/symbol_uploads, api_path: v0.1/apps/{owner_name}/{app_name}/symbol_uploads, beacon: crash, code: ETIMEDOUT. Correlation ID: [redacted]"
```

But the build still finishes successfully. After digging into the [code](https://github.com/microsoft/fastlane-plugin-appcenter/blob/master/lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb#L121), it seems only a `401` response, when uploading a dSYM, will throw an error and cause the build to fail.

We would prefer for an error to be thrown, if the dSYM failed to upload. Is it possible to make this change? Is there a reason to not do so?

**Comment by kokenjr** [comment] 2020-12-03 14:27
Bump. Anyone able to help with this?

**Comment by DmitriyKirakosyan** [comment] 2022-07-08 03:30
Hi @kokenjr , the plugin uploads release first and then it tries to upload mapping and dsym. So, it is by design that uploading dsym can't affect the upload of the build.

If you want to prevent uploading a build if uploading dsym was not successful, you can try to split your command into two commands: upload dsym and upload release, using the flags `upload_dsym_only` and `upload_build_only` and perform actions according to the command output.

I'm closing this issue, but please let me know if you find it not helpful and the question is still relevant for you.

**Closed by DmitriyKirakosyan** 2022-07-08 03:30 UTC
Labels: probable-bug
