### ISSUE TITLE
version problen in ipa

### ISSUE THREAD

**Issue by logemann** [microsoft/fastlane-plugin-appcenter#53] opened 2019-02-21 12:07 UTC
Hi,

i have some kind of version problem. The error in fastlane-appcenter-plugin is:

`Error uploading binary 422: {"status"=>"error", "message"=>"Version could not be created from build. Please make sure that your .ipa file has the correct format."}`

How can i check what the real problem is. Normally the flutter build pipeline should add the current version into the Info.plist file of the resulting image. Or does appcenter look into a different file for the version?

**Comment by alextkd** [comment] 2019-05-01 08:19
@logemann I managed to get to the bottom of it. The problem is caused by the app signing. You need to sign the app with the same provisioning profile and distribution that you've uploaded to Appcenter .mobileprovision and .p12
So once your gym() is configured to take the right signing will work. I've exported manually an ipa file that was signed with it and ran the appcenter_upload task only and it worked perfectly

**Comment by slxl** [comment] 2019-09-16 15:38
for me this problem appeared when I've added the build phase script to increment a build number:

```
buildNumber=$(git rev-list --count master..)
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $buildNumber" "$INFOPLIST_FILE"
```
while everything seems to be fine when you replace "master.." with "HEAD"

**Comment by jpeg-ms** [comment] 2019-10-01 10:34
Hey, I will close this as the issues seem not directly related to this plugin, but rather to a config mismatch. Please re-open if there's an issue in this fastlane plugin.

**Closed by jpeg-ms** 2019-10-01 10:34 UTC
