### ISSUE TITLE
A problem occurred while extracting your app

### ISSUE THREAD

**Issue by juancruzgs** [microsoft/fastlane-plugin-appcenter#243] opened 2020-09-21 18:38 UTC
I randomly get the error `A problem occurred while extracting your app` while uploading an Android APK.
It's usually fixed by re-running the workflow in the CI environment, but I'd like to know why it happens.

I'm using version `1.9.0` of this plugin.

Lane:
```
  desc "Submit APK to AppCenter"
  lane :android_alpha_apk do |options|
    changeLogs = format_last_commit

    appcenter_upload(
      api_token: options[:apiToken],
      owner_name: options[:ownerName],
      app_name: options[:appName],
      notify_testers: false,
      destinations: options[:destinations],
      release_notes: changeLogs,
      file: options[:apkPath]
    )
  end
```

Logs:
```
[01:01:39]: [32m------------------------------[0m
[01:01:39]: [32m--- Step: appcenter_upload ---[0m
[01:01:39]: [32m------------------------------[0m
[01:01:40]: Starting release upload...
[01:01:41]: Setting Metadata...
[01:01:43]: Metadata set
[01:01:43]: Uploading release binary...
[01:01:45]: Chunk uploaded
[01:01:46]: Chunk uploaded
[01:01:47]: Chunk uploaded
[01:01:49]: Chunk uploaded
[01:01:50]: Chunk uploaded
[01:01:51]: Chunk uploaded
[01:01:53]: Chunk uploaded
[01:01:54]: Chunk uploaded
[01:01:56]: Chunk uploaded
[01:01:57]: Chunk uploaded
[01:01:58]: Chunk uploaded
[01:02:00]: Chunk uploaded
[01:02:01]: Chunk uploaded
[01:02:02]: Chunk uploaded
[01:02:04]: Chunk uploaded
[01:02:05]: Chunk uploaded
[01:02:05]: Binary uploaded
[01:02:05]: Finishing release...
[01:02:05]: Upload finished
[01:02:06]: Waiting for release to be ready...
[01:03:12]: [31mError fetching release: A problem occured while extracting your app. (Correlation ID: 8f37593f-e412-4a10-8aca-7ba8530dfdaf)[0m
```

**Comment by kokhlo** [comment] 2020-11-16 07:14
Hello everyone,

I have this issue as well, anyone know how to mitigate it?

**Comment by iceproductionz** [comment] 2020-11-22 22:24
Having a similar issue on appcenter cli, today 

Release upload failed
Release upload was aborted
Error: Loading release id failed: A problem occured while extracting your app. (Correlation ID: ed6c2b5f-feeb-4e18-9c1b-c11d509413f7)

**Comment by bamboozila** [comment] 2020-12-02 15:55
Same here ! Uploading the apk manually works fine.

**Comment by renatoeufe** [comment] 2020-12-10 14:51
@iceproductionz I'm experiencing the same issue here, even when uploading the .ipa manually. Any thoughts?

**Comment by ZackOPP** [comment] 2021-01-07 09:05
Same here. I'm using the appcenter plugin version `1.11.0`

**Comment by iceproductionz** [comment] 2021-01-07 14:55
I worked it out to be on Android related to APK version being set correct

android/app/build.gradle
```
defaultConfig {
        applicationId "com.space.app.AppName"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode versionProps['VERSION_BUILD'].toInteger()
        versionName versionProps['VERSION_NAME']
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
```
where version build is
VERSION_BUILD = 8
VERSION_NAME = 1.1.0

For IOS
```
      /usr/libexec/Plistbuddy -c "Set CFBundleVersion 8" "ios/App/App/Info.plist"
      /usr/libexec/Plistbuddy -c "Set CFBundleShortVersionString 1.1.0" "ios/App/App/Info.plist"
```
This was based on using Capacitor for creating Android and IOS build.

**Comment by niparx** [comment] 2021-01-14 14:08
Same issue. Uploading apk. Appcenter plugin version `1.11.0`.
I must say, that APK has valid versionCode and versionNumber. Such issues does not happens all the time with same code.
`[13:24:46]: Uploading release binary...
[13:24:49]: Chunk uploaded
[13:24:52]: Chunk uploaded
[13:24:55]: Chunk uploaded
[13:24:58]: Chunk uploaded
[13:25:00]: Chunk uploaded
[13:25:03]: Chunk uploaded
[13:25:06]: Chunk uploaded
[13:25:09]: Chunk uploaded
[13:25:11]: Chunk uploaded
[13:25:11]: Binary uploaded
[13:25:11]: Finishing release...
[13:25:12]: Upload finished
[13:25:13]: Waiting for release to be ready...
[13:26:41]: [31mError fetching release: A problem occured while extracting your app. (Correlation ID: 614c0a9c-c27e-46a6-8ef1-f3d025de722c)[0m`

**Comment by simontgs** [comment] 2021-01-20 21:33
Same, we're experiencing this issue. On Android. Any update on when this will likely be addressed? 1.11.0 plugin

thnx

**Comment by PawKanarek** [comment] 2021-01-22 11:08
Do you have some workarounds? What's wrong with my apk?

**Comment by niparx** [comment] 2021-01-22 14:22
@PawKanarek for us it was randomly: sometimes it was ok, sometimes - error

**Comment by TobiasJoergensen** [comment] 2021-02-09 10:34
I am experiencing the same. It's a 50/50 if we get this error, but funny enough it's only for one of our projects that it fails - the other 3 works fine every time. It might be related to a specific setting.

**Comment by PetrBodnar** [comment] 2021-02-15 10:27
We got same problem with uploading iOS builds.
Sometimes uploading is ok, sometimes - we have this error.

npm 6.14.4  
appcenter-cli 2.7.3

Correlation ids:   18711d30-da7d-4d0d-b349-532fe457d1c1,  15723071-c248-42c5-bb04-9311dc7a5f6b, bdd785a1-ce23-4682-ac77-af2bb9abf04b

**Comment by PetrBodnar** [comment] 2021-02-15 10:31
We got similar problem with uploading iOS builds (we are using appcenter-cli, not using fasltane plugin).
Sometimes uploading is ok, sometimes - we have this error.

npm 6.14.4  
appcenter-cli 2.7.3

Correlation ids:   18711d30-da7d-4d0d-b349-532fe457d1c1,  15723071-c248-42c5-bb04-9311dc7a5f6b, bdd785a1-ce23-4682-ac77-af2bb9abf04b

**Comment by johngun3** [comment] 2021-02-16 20:48
My organization has seen a big improvement in upload success of android APKs via fastlane app center plugin after we were able to drastically reduce the size of our app from ~340MB to ~180MB last week. We are still seeing upload failures but the failure rate has dropped dramatically. Just wanted to offer this data point since we've been struggling with this issue for a while.

**Comment by avinash-ivy** [comment] 2021-02-18 05:09
We are facing the same issue with our app.
Our ipa file size is quite huge and it usually takes 100 mins to upload to appcenter. After waiting for 100 mins, if these kind of error pops up, it is really frustrating.
As of now, we have optimized our app in terms of size and we can't get it further down. We are not using app slicing for AppCenter, however we are doing it for AppStore/Testflight uploads.

```
Log of the error:
[02:30:42]: Chunk uploaded
[02:30:45]: Chunk uploaded
[02:30:50]: Chunk uploaded
[02:31:15]: Chunk uploaded
[02:31:27]: Chunk uploaded
[02:31:41]: Chunk uploaded
[02:31:55]: Chunk uploaded
[02:32:00]: Chunk uploaded
[02:32:00]: Binary uploaded
[02:32:00]: Finishing release...
[02:32:01]: Upload finished
[02:32:03]: Waiting for release to be ready...
[02:42:52]: Error fetching release: A problem occured while extracting your app. (Correlation ID: 851bac0f-7cd7-445d-805f-7cdd4f34b6ec)
```

Any help would be deeply appreciated.

**Comment by jesusmateos1234** [comment] 2021-02-18 11:45
How it's going this issue?  In appcenter dashboard happen the same ...

**Comment by mr-gil** [comment] 2021-03-18 15:54
This continue happening !!!!!!!   It fails each day !

**Comment by tunds** [comment] 2021-03-26 08:51
We're also getting this issue, seems to be happening intermittently like there is currently a 30% the plugin will actually work 😪

**Comment by thomaskellough** [comment] 2021-04-07 16:49
This may or may not help some people. But ensure you have the App Name correct in your Ruby script. It's may not be what it looks like in AppCenter, but it should be a specific name in the URL. I noticed this when I had an iOS version and then an Android version of the same app. Since Android was created second, the URL adds a "-1" at the end of the URL. For example:

https://appcenter.ms/orgs/COMPANYNAME/apps/APPNAME-1

So your appcenter_upload() would look something like...

    appcenter_upload(
      api_token: "APITOKEN",
      owner_name: "APPCENTER OWNER",
      app_name: "APPNAME-1",
      file: "app/build/outputs/apk/#{flavor}/release/app-#{flavor}-release.apk",
      destinations: "Testers",
      release_notes: notes,
      notify_testers: true
    )

After editing the app_name the ruby script I was able to successfully upload.

**Comment by GoryaBar** [comment] 2021-04-15 13:50
Facing the same issue. In our team, we use TeamCity, and today I build have been failed twice.

**Comment by KanniyappanP** [comment] 2021-08-19 04:05
I have this issue, but it occurs in Windows OS and i am trying to manually upload WinUI Desktop app (.msixbundle) in appcenter, anyone know how to solve this it?  or any workaround would be appreciated.

https://github.com/microsoft/microsoft-ui-xaml/issues/5705

Thanks in advance.

**Comment by YassinELhadedy** [comment] 2021-09-02 14:51
[14:44:18]: Starting release upload...
[14:44:18]: Setting Metadata...
[14:44:18]: Metadata set
[14:44:18]: Uploading release binary...
[14:44:18]: Chunk uploaded
[14:44:18]: Binary uploaded
[14:44:18]: Finishing release...
[14:44:18]: Upload finished
[14:44:18]: Waiting for release to be ready...
[14:44:25]: Error fetching release: A problem occured while extracting your app. (Correlation ID: f9dbb152-a359-4990-8ef9-82cbd88ed14e)
+-------------------------------------+--------------------------------------------------------------------------------------------------

**Comment by akanksha820** [comment] 2021-10-01 16:19
Same issue here
Can we have the fix asap please?

**Comment by aslheyrr** [comment] 2021-10-01 16:35
I'm facing the same issue. Plugin version 1.11.1

**Comment by mohammad-yousuf** [comment] 2022-07-04 21:46
Use this bash script to automate VS app center distribution:

npm install --location=global appcenter-cli

appcenter distribute release \
    --group Collaborators \
    --file <file path(apk, ipa, pkg etc> \
    --release-notes 'App Submission' \
    --app <app slug (just like in app center distribute task)> \
    --token <API token> \
    --build-version 1.0 \
    --build-number 1.0 \
    --quiet

**Comment by DmitriyKirakosyan** [comment] 2022-07-08 06:39
Hi @juancruzgs and everyone who experiences this issue,

AppCenter fastlane plugin doesn't build your app, it only uploads the app binary to the AppCenter portal.
If you receive `A problem occurred while extracting your app`, this means the backend doesn't like the app structure and it will also happen if you try to upload the file manually. In this case please [contact the AppCenter support team](https://docs.microsoft.com/en-us/appcenter/help).

I'm closing this issue as not related to the appcenter fastlane plugin, but please let me know if you still think the problem is related to the plugin.

**Closed by DmitriyKirakosyan** 2022-07-08 06:39 UTC
Labels: bug
