### ISSUE TITLE
Upload a release disabled

### ISSUE THREAD

**Issue by davebcn87** [microsoft/fastlane-plugin-appcenter#133] opened 2019-10-17 09:00 UTC
Hey,

I'm using this plugin to upload to AppCenter and I'm missing one option that the HockeyApp plugin had. In HockeyApp I was able to upload a release in "restricted" mode [1], so the build was pushed but yet not public. I see that the AppCenter API has an option "enabled" that we can set to false. 

Is it possible that this parameter is not available in the Fastlane AppCenter plugin?

[1]

Key | Description | Default 
-----------|-------------|------------
status | Download status: "1" = No user can download; "2" = Available for download (only possible with full-access token) | 2

**Comment by davebcn87** [comment] 2019-10-17 09:14
Yes, exactly. I can try to implement it and create a pull request if you prefer.

**Comment by davebcn87** [comment] 2019-10-17 09:24
I'll try and let you know :)

**Comment by davebcn87** [comment] 2019-10-17 15:02
@jpeg-ms I was able to upload a build as enabled: false, but then it looks like cannot be added in a distribution group because is disabled:
```
Error adding to group 400: {"code"=>"bad_request", "message"=>"Error: Requested release 1568 is disabled and cannot be distributed."}
```

Any suggestions with that?

**Comment by jpeg-ms** [comment] 2019-10-18 00:57
Hey @davebcn87,

This sounds about right, indeed, though I didn't know about this behavior (but I can confirm from the code that this is expected behavior). I think the concept of enabled/disabled releases might be a bit different from what it was in HockeyApp.

I believe that the preferred way in App Center to create a release without publishing it is to have an empty group and distribute to it. Once you're ready to "enable" the release, you just distribute it to other groups. 

You would disable a release iif it turns out "bad" and you don't want to just completely delete it. Also note that a disabled release is disabled for all groups.

So I'm curious about your workflow and why specifically need to disable releases.

**Comment by davebcn87** [comment] 2019-10-18 07:43
Hey @jpeg-ms,

thanks for your message. I will explain my use case for disabled releases. As you wrote this message I was thinking that maybe we don't need the enhancement because our workflow is like this:
- Create a release internally (with a list of internal testers)
- When we feel it's ready, we make the release public (using the public link).
- We stop the release at different steps (disabling the release) so we can do a gradual rollout to detect problems. 

With hockeyapp we pushed the release disabled, an we distributed using the web portal. Maybe now we can already distribute it to the internal users while creating and we don't need to make it disabled.

Once I push a release to an internal distribution group I can change it in AppCenter Portal to make it public?

**Comment by jpeg-ms** [comment] 2019-10-18 07:47
Your workflow sounds pretty standard to me. You can definitely use non public groups when publishing and then manually publishing to public groups. By default this plugin will distribute to the Collaborators group, which is the default group for any app.

> Once I push a release to an internal distribution group I can change it in AppCenter Portal to make it public?

That's absolutely right. You can't do this with the fastlane plugin, but you can do it either on the web portal or using the CLI (using `appcentger distribute releases add-destination`).

**Comment by davebcn87** [comment] 2019-10-18 07:59
Amazing, I'll try to do it like that. Other than that, I already have the code to push it disabled. Do you think makes sense that I create a pull request?

**Comment by jpeg-ms** [comment] 2019-10-18 08:09
After our conversation yesterday, I figured that maybe you weren't aware of this flow. So, I don't think we really need this feature now, as this isn't exactly in line with how releases are meant to work on App Center.

**Comment by jpeg-ms** [comment] 2019-11-14 04:42
Closing this for now. In App Center we don't usually need to create disabled releases.

**Closed by jpeg-ms** 2019-11-14 04:42 UTC
Labels: enhancement
