### ISSUE TITLE
Option notify_testers also disabled Slack notifications

### ISSUE THREAD

**Issue by Dids** [microsoft/fastlane-plugin-appcenter#63] opened 2019-04-16 13:04 UTC
I'm not sure if this is intended behavior, but since `notify_testers` is now `false` by default, this will disable both email and Slack notifications for new distributions.

It took me a while to figure this one out, because the notifications just magically stopped working, which makes me wonder if `notify_testers` being `false` _by default_ is the intended/best option here?

**Comment by derpixeldan** [comment] 2019-04-16 13:08
The intention of having it set to `false` by default is to prevent sending notifications to testers by accident. However, this shouldn't influence webhooks.

**Comment by Dids** [comment] 2019-04-16 13:11
In my case distribution Slack notifications magically stopped working about a week ago, and I just managed to fix them by simply adding `notify_testers: true` to my `Fastfile`, which does make me think it's related, unless it was a coincidence and caused by temporary connection issues elsewhere? Either way, my distributions went through to App Center just fine, but the notifications didn't. Both email and Slack notifications stopped working at the same time.

**Comment by derpixeldan** [comment] 2019-04-16 13:13
Glad you got things working again and thanks for reporting this. We're looking into it.

**Comment by derpixeldan** [comment] 2019-04-16 13:40
We could reproduce it and track it as a bug.

**Comment by oklimberg** [comment] 2019-05-09 10:25
Is this releated to the code of this plugin or is it an API problem of AppCenter itself?
Since I stumbled into this issue as well, I would like to have a look, if I could fix this within the plugin.

Best Regards

**Comment by derpixeldan** [comment] 2019-05-09 10:41
It's not a problem of the plugin, it's actually a bug in App Center.

**Comment by jpeg-ms** [comment] 2019-10-01 10:29
Hey @derpixeldan, did we get this fixed?

**Comment by jpeg-ms** [comment] 2019-10-01 10:30
I will close this ticket, assuming that was fixed in App Center. Also this was not immediately related to the plugin.

**Closed by jpeg-ms** 2019-10-01 10:30 UTC
