### ISSUE TITLE
Upload not working, App not found

### ISSUE THREAD

**Issue by nochill-lp** [microsoft/fastlane-plugin-appcenter#307] opened 2022-09-29 07:24 UTC
on a project I setup with fastlane a lane to build an android app and publish it on appcenter.

Here a snippet of the lane, where, for the sake of simplicity, I surround by curly brackets protected data:

```
lane :buildAndDeploy do
  gradle(task: "clean assembleRelease")
  appcenter_upload(
      app_name: "{myappname}",
      api_token: "{token}",
      owner_name: "{ownername}",
      owner_type: "user", 
      file: "{filePath}"
    )
```

Everything worked like a charm till two weeks ago, when suddently it stops working. When the lane cruise to the appcenter upload step I receive this from the plugin.

```
------------------------------
--- Step: appcenter_upload ---
------------------------------
App with name {appname} not found, create one? (y/n)
```

as indicated in the documentation the app name and owner name are populated like this:

**https://appcenter.ms/users/{ownername}/apps/{appname}**

Any idea of what could have happened in the past two weeks? I didn't change anything both on the Fastfile and the Appcenter project.

**Comment by DmitriyKirakosyan** [comment] 2022-09-29 07:49
Hi @nochill-lp , thank you for reaching out!
Can you try to perform `appcenter login` with the api token used for fastlane, then perform `appcenter apps list` and check if your app is displayed in the list?

**Comment by nochill-lp** [comment] 2022-09-29 08:27
Hi @DmitriyKirakosyan i run the script and the result is:

{ownername}/{appname} 

both equals to what I have in the owner_name and app_name property of the plugin.

**Comment by DmitriyKirakosyan** [comment] 2022-09-30 02:58
@nochill-lp Do you have any special symbols in your app name?

**Comment by nochill-lp** [comment] 2022-10-03 08:39
Hi @DmitriyKirakosyan only an underscore. The name is something like this: Client_android

**Comment by DmitriyKirakosyan** [comment] 2022-10-04 04:49
Hi @nochill-lp , what about the owner name, does it contain any special characters? Also, could you check if the owner name and app name are matched to these you see in the browser url when opening it on the App Center portal? Also, check if `owner_type` is set correctly.

**Comment by Ro-M** [comment] 2022-10-04 22:38
Hi! Just chiming in here to confirm that we are also seeing the same issue in our organisation. Our last successful upload to AppCenter was on September 30th, so it started to surface around the same time.

I double checked the `owner_type`, `app_name` and `api_token` that we are providing to the `appcenter_upload` lane - They are matching those that we see in the browser url when we open the app on the AppCenter portal. Additionally I tried the following
- with AppCenter CLI, run `appcenter apps list --token <MY_TOKEN>` and it's producing the app that fastlane tells me is not there (I'm using the same token here as before)
- with AppCenter CLI, run `appcenter apps show --token <MY_TOKEN> --app <M_OWNER_NAME>/<MY_APP_NAME>` and it shows the correct app
- For good measure run the following curl command and it works as well
```
curl -X 'GET' \
  'https://api.appcenter.ms/v0.1/apps/<MY_OWNER_NAME>/<MY_APP_NAME>' \
  -H 'accept: application/json' \
  -H 'X-API-Token: <MY_APP_TOKEN>'
```

Some more info:
- `owner_name` contains `-` but no other special chars, like `hockeyapp-a2ft`
- `app_name` contains `-` but not other special chars, like `SomApp-iOS-Feature`
- `api_token` is a user token with full access created with my user
- The app in question is part of an organisation in which my user has the `admin` role
- This issue extends to all the apps within the organisation

Please let me know how I can be of more help in solving this. Any help or support from your side is much appreciated. 🙇‍♂️

**Comment by DmitriyKirakosyan** [comment] 2022-10-05 08:43
@Ro-M , thank you for the details! Could you try to enable debug logs by passing `DEBUG=1` environment variable and check if URL in logs is matched the one you used with `curl`?

**Comment by nochill-lp** [comment] 2022-10-05 09:57
@DmitriyKirakosyan just to confirm that owner_name hasn't ant special character and owner_type is set correctly.

**Comment by DmitriyKirakosyan** [comment] 2022-10-06 04:56
@nochill-lp , please try to enable debug logs by passing `DEBUG=1` as well and check if you can get the app info using the URL in logs. Plugin calls the API with URL composed based on the `appcenter_upload` action properties, so it shouldn't be any difference between calling it manually with curl or running the plugin action.

Actually, there were no related changes in fastlane plugin recently, so I think there were changes on the backend side which might affect you. I would also recommend you to [contact support](https://learn.microsoft.com/en-us/appcenter/help) for faster resolution of this issue.

**Comment by nochill-lp** [comment] 2022-10-07 15:57
Hi @DmitriyKirakosyan , folowing your suggestion i run the `appcenter apps list --token <MY_TOKEN> --debug` and I discovered that the token I was using it didn't belong to the owner of the project, instead it belongs to a different user who has been removed from the project.

Adding a new API token resolved the issue.
Thanks again for your help, I hope this can help also @Ro-M

**Comment by Ro-M** [comment] 2022-10-07 19:24
Weird coincidence, it was the same on our end 😞 Although it was a bit more tricky because the issue was that the CI system we are using was apparently not correctly updating the token secret. It showed us the correct secret to be used but then used the old one instead...

Thanks for your help @DmitriyKirakosyan and sorry for the hassle 🙇‍♂️

**Comment by DmitriyKirakosyan** [comment] 2022-10-09 18:47
I'm glad the issue is resolved for you guys. Feel free to reach out!
Closing.

**Closed by DmitriyKirakosyan** 2022-10-09 18:47 UTC
